### ISSUE TITLE
I utilize the project in https://github.com/vvilhonen/cargo-aws-lambda

### ISSUE THREAD

**Issue by vvilhonen** [softprops/lambda-rust#45]
Do you think it would make sense to reference it in README here?

**Comment by softprops** [comment]
oh nice. I sry I missed the message. feel free to drop a pr. very nice work

**Comment by vvilhonen** [comment]
Thanks for the amazingly useful docker builder! This just adds couple of lines of rusoto code to deploy the product. The PR can be found here https://github.com/softprops/lambda-rust/pull/48
