### ISSUE TITLE
Skip mv if bin name is named bootstrap in cargo

### ISSUE THREAD

**Issue by softprops** [softprops/lambda-rust#7]
ctx https://github.com/softprops/lambda-rust/issues/2#issuecomment-461921860

mv bootstrap bootstrap is a trap

**Comment by j0ni** [comment]
Can you push a new `latest` image to the docker registry please?

I have workarounds, but I'd love to get rid of them :) thanks!

**Comment by softprops** [comment]
will publish in a bit. was going to try and get one more thing it but I think it can wait. In the meantime unless your crate is called `bootstrap` you can just use the default crate binary sans the extra configuration

**Comment by softprops** [comment]
published there should be a new docker tag `v0.2.1-rust-1.32.0` which the `latest` tag as an alias. I'll be rolling that out to https://github.com/softprops/serverless-rust next
